<a href="https://colab.research.google.com/github/Missboonyos/BC12_Essential_Python_for_DA1/blob/main/BC12_Essential_Python_for_DA1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Essential Python for DA**

- Object Oriented Programming
- Read and Write file
- Context Manager
- Handle Error
- Pandas & Numpy (on demand)
- Request API

# OOP

In [ ]:
class Dog:
  def __init__(self, name, species, age):
    self.name = name
    self.species = species
    self.age = age

  def bark(self):
    print(f"{self.name} is barking 'wang wang'!")

  def birthday(self):
    self.age += 1

In [ ]:
# attributes
dog1 = Dog("I'Pui", "TH Puntang", 2)
dog2 = Dog("Judy", "Beagle", 1)

In [ ]:
dog1.bark()
dog2.bark()

I'Pui is barking 'wang wang'!
Judy is barking 'wang wang'!

In [ ]:
dog1.name

"I'Pui"

In [ ]:
print(f"{dog1.name} is {dog1.species} and he is {dog1.age} year(s) old")
print(f"{dog2.name} is {dog2.species} and she is {dog2.age} year(s) old")

I'Pui is TH Puntang and he is 2 year(s) old
Judy is Beagle and she is 1 year(s) old

In [ ]:
print(dog1.age)
dog1.birthday()
print(dog1.age)

2
3

# OOP Summary
comprises
- attributes: name, species, age
- methods: function; bark() birthday()

### HW. Create ATM with at least 5 functions by using OOP

- deposit, withdraw, check balance, OTP, order coffee, pay bill, internet, etc.

In [ ]:
class ATM:
  def __init__(self, username, bank, balance):
    self.username = username
    self.bank = bank
    self.balance = balance

  def __str__(self):
    return f"{self.username} uses {self.bank} and has EUR {self.balance} in the account."

  def check_balance(self):
    print(f"Your balance is EUR {self.balance}")

  def deposit(self, amount):
    self.balance += amount
    print(f"Deposit EUR {amount} successfully!")

  def withdraw(self, amount):
    self.balance -= amount
    print(f"Withdraw EUR {amount} sucessfully")

  def order_coffee(self, amount):
    self.balance -= amount
    print(f"Order coffee with EUR {amount} successfully")

  def pay_internet(self, amount):
    self.balance -= amount
    print(f"Pay internet with EUR {amount} successfully")

  def pay_bill(self, amount):
    self.balance -= amount
    print(f"Pay bill with EUR {amount} successfully")

  def donation(self, amount):
    self.balance -= amount
    print(f"You donate EUR {amount} successfully")

  def otp(self, otp):
    print(f"Your OTP is {otp}")

In [ ]:
lila = ATM("lilapurple", "kbank", 1000)

In [ ]:
print(f"{lila.username} is opening a new bank account at {lila.bank} with the amount of EUR {lila.balance}")

lilapurple is opening a new bank account at kbank with the amount of EUR 1000

In [ ]:
lila.check_balance()

Your balance is EUR 1000

In [ ]:
lila.deposit(200)

Deposit EUR 200 successfully!

In [ ]:
lila.check_balance()

Your balance is EUR 1200

In [ ]:
lila.withdraw(100)

Withdraw EUR 100 sucessfully

In [ ]:
lila.check_balance()

Your balance is EUR 1100

In [ ]:
lila.order_coffee(13)
lila.pay_internet(8)
lila.pay_bill(20)
lila.donation(10)

Order coffee with EUR 13 successfully
Pay internet with EUR 8 successfully
Pay bill with EUR 20 successfully
You donate EUR 10 successfully

In [ ]:
lila.check_balance()

Your balance is EUR 1049

In [ ]:
lila.otp(1224)

Your OTP is 1224

In [ ]:
print(lila)

lilapurple uses kbank and has EUR 1049 in the account.

In [ ]:
# Superclass
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

## extension
class Employee(Person):
  def __init__(self, name, age, company):
    super().__init__(name, age)
    self.company = company

  def greeting(self):
    print("Hello World!")

In [ ]:
person1 = Person("Lila", 20)

In [ ]:
person2 = Employee("Rose", 25, "DB")

In [ ]:
person2.greeting()

Hello World!

# Try Except Block

In [ ]:
try:
  result = 1/0
except:
  print("Cannot divide by zero!")
else:
  print("Wrong data type!")

Cannot divide by zero!

In [ ]:
!pwd

/content

In [ ]:
!ls

hotel.csv  sample_data

In [ ]:
!cat hotel.csv

hotel_id,name,city,star_rating,price_per_night
101,Grand Plaza,New York,5,350
102,Ocean View,Miami,4,220
103,Mountain Retreat,Denver,4,185
104,The Urban Stay,Chicago,3,140
105,Sunset Resort,Los Angeles,5,410
106,Desert Inn,Phoenix,3,95
107,Heritage House,Boston,4,210
108,Lakeside Lodge,Seattle,3,130
109,Golden Gate Suites,San Francisco,5,380
110,Central Boutique,Austin,4,195

In [ ]:
## read file
import csv

In [ ]:
## r = read, w = write, a = append
try:
  file = open("hotel.csv", "r")
## module function
## csv.reader()
  data = csv.reader(file)
  for row in data:
    print(row)
  file.close()

except FileNotFoundError:
  print("File not found! Please check file name again.")
finally:
  print("read file successfully")

['hotel_id', 'name', 'city', 'star_rating', 'price_per_night']
['101', 'Grand Plaza', 'New York', '5', '350']
['102', 'Ocean View', 'Miami', '4', '220']
['103', 'Mountain Retreat', 'Denver', '4', '185']
['104', 'The Urban Stay', 'Chicago', '3', '140']
['105', 'Sunset Resort', 'Los Angeles', '5', '410']
['106', 'Desert Inn', 'Phoenix', '3', '95']
['107', 'Heritage House', 'Boston', '4', '210']
['108', 'Lakeside Lodge', 'Seattle', '3', '130']
['109', 'Golden Gate Suites', 'San Francisco', '5', '380']
['110', 'Central Boutique', 'Austin', '4', '195']
read file successfully

In [ ]:
# context manager
read_data = []

with open("hotel.csv", "r") as file:
  data = csv.reader(file)
  for row in data:
    read_data.append(row)

In [ ]:
read_data

[['hotel_id', 'name', 'city', 'star_rating', 'price_per_night'],
 ['101', 'Grand Plaza', 'New York', '5', '350'],
 ['102', 'Ocean View', 'Miami', '4', '220'],
 ['103', 'Mountain Retreat', 'Denver', '4', '185'],
 ['104', 'The Urban Stay', 'Chicago', '3', '140'],
 ['105', 'Sunset Resort', 'Los Angeles', '5', '410'],
 ['106', 'Desert Inn', 'Phoenix', '3', '95'],
 ['107', 'Heritage House', 'Boston', '4', '210'],
 ['108', 'Lakeside Lodge', 'Seattle', '3', '130'],
 ['109', 'Golden Gate Suites', 'San Francisco', '5', '380'],
 ['110', 'Central Boutique', 'Austin', '4', '195']]

In [ ]:
# header
read_data[0]

['hotel_id', 'name', 'city', 'star_rating', 'price_per_night']

In [ ]:
# body data
read_data[1: ]

[['101', 'Grand Plaza', 'New York', '5', '350'],
 ['102', 'Ocean View', 'Miami', '4', '220'],
 ['103', 'Mountain Retreat', 'Denver', '4', '185'],
 ['104', 'The Urban Stay', 'Chicago', '3', '140'],
 ['105', 'Sunset Resort', 'Los Angeles', '5', '410'],
 ['106', 'Desert Inn', 'Phoenix', '3', '95'],
 ['107', 'Heritage House', 'Boston', '4', '210'],
 ['108', 'Lakeside Lodge', 'Seattle', '3', '130'],
 ['109', 'Golden Gate Suites', 'San Francisco', '5', '380'],
 ['110', 'Central Boutique', 'Austin', '4', '195']]

In [ ]:
## for loop to calculate avg. price per night
price = []

for row in read_data[1: ]:
  price.append(float(row[4])) ## -1 the last item

avg_price = sum(price) / len(price)
print(f"The average price per night is EUR {avg_price}")

The average price per night is EUR 231.5

In [ ]:
## another way to write avg price calculation
price = []

for row in read_data[1: ]:
  price.append(int(row[4])) ## -1 the last item

print(f"Average price per night: {sum(price)/len(price)}")

Average price per night: 231.5

In [ ]:
# Modern Python using Pandas
import pandas as pd

df = pd.read_csv("hotel.csv")

df.head()

   hotel_id              name         city  star_rating  price_per_night
0       101       Grand Plaza     New York            5              350
1       102        Ocean View        Miami            4              220
2       103  Mountain Retreat       Denver            4              185
3       104    The Urban Stay      Chicago            3              140
4       105     Sunset Resort  Los Angeles            5              410

In [ ]:
df.price_per_night.mean()

np.float64(231.5)

In [ ]:
# or this way
df["price_per_night"].mean()

np.float64(231.5)

# Read & Write Files

In [1]:
import csv

In [2]:
# write file + context manager
head = ["id", "name", "city"]
body = [
    [1, "CU", "Bangkok"],
    [2, "LSE", "London"],
    [3, "Reading", "Reading"]
]

with open("school.csv", "w") as file:
  writer = csv.writer(file)
  writer.writerow(head)
  writer.writerows(body)

In [3]:
!cat school.csv

id,name,city
1,CU,Bangkok
2,LSE,London
3,Reading,Reading

In [4]:
# modern Python, using Pandas
import pandas as pd

df = pd.read_csv("school.csv")
df.head()

   id     name     city
0   1       CU  Bangkok
1   2      LSE   London
2   3  Reading  Reading

In [5]:
# export csv file in pandas
# another way to export
# df.to_csv("school2.csv")
df.to_csv("school2.csv", index=False)

In [6]:
!ls

sample_data  school2.csv  school.csv

In [7]:
!cat school2.csv

id,name,city
1,CU,Bangkok
2,LSE,London
3,Reading,Reading

In [8]:
# read data from the internet
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/penguins.csv"

In [10]:
# import pandas as the whole library
import pandas as pd

df_penguins = pd.read_csv(url)
df_penguins.head()
df_penguins.tail()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [12]:
# import pandas as read_csv
from pandas import read_csv

df_penguins = read_csv(url)
df_penguins.head()
df_penguins.tail()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [13]:
## select column
df_penguins[["species", "island", "body_mass_g"]].head(10)

  species     island  body_mass_g
0  Adelie  Torgersen       3750.0
1  Adelie  Torgersen       3800.0
2  Adelie  Torgersen       3250.0
3  Adelie  Torgersen          NaN
4  Adelie  Torgersen       3450.0
5  Adelie  Torgersen       3650.0
6  Adelie  Torgersen       3625.0
7  Adelie  Torgersen       4675.0
8  Adelie  Torgersen       3475.0
9  Adelie  Torgersen       4250.0

In [15]:
## filter row
df_penguins.query("species == 'Adelie' and island == 'Torgersen'").head(5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

In [17]:
## select column then filter row
df_penguins[["species", "island", "body_mass_g"]]\
      .query("species == 'Adelie' and island == 'Dream'")\
      .head(5)

   species island  body_mass_g
30  Adelie  Dream       3250.0
31  Adelie  Dream       3900.0
32  Adelie  Dream       3300.0
33  Adelie  Dream       3900.0
34  Adelie  Dream       3325.0

In [ ]:
# ### compare R vs Python
# # R
# df %>%
#   select() %>%%
#   filter() %>%
#   arrange()

# # Python
# df.select() \
#   .filter() \
#   .arrange()

In [18]:
## filter without query()
df_penguins[df_penguins.species == "Adelie"]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
147,Adelie,Dream,36.6,18.4,184.0,3475.0,FEMALE
148,Adelie,Dream,36.0,17.8,195.0,3450.0,FEMALE
149,Adelie,Dream,37.8,18.1,193.0,3750.0,MALE
150,Adelie,Dream,36.0,17.1,187.0,3700.0,FEMALE
151,Adelie,Dream,41.5,18.5,201.0,4000.0,MALE

In [25]:
## filter without query()
df_penguins[df_penguins['body_mass_g'] >= 4500][\
    ["species", "sex", "body_mass_g"]]

    species     sex  body_mass_g
7    Adelie    MALE       4675.0
17   Adelie    MALE       4500.0
39   Adelie    MALE       4650.0
45   Adelie    MALE       4600.0
81   Adelie    MALE       4700.0
..      ...     ...          ...
338  Gentoo  FEMALE       4925.0
340  Gentoo  FEMALE       4850.0
341  Gentoo    MALE       5750.0
342  Gentoo  FEMALE       5200.0
343  Gentoo    MALE       5400.0

[118 rows x 3 columns]

# Request API

How to get data via API the easy way

In [26]:
# Request API
import requests

## api endpoint
url = "https://swapi.info/api/people/1"

In [27]:
requests.get(url)

In [28]:
## assign value to response
response = requests.get(url)

In [29]:
response.json()

{'name': 'Luke Skywalker',
 'height': '172',
 'mass': '77',
 'hair_color': 'blond',
 'skin_color': 'fair',
 'eye_color': 'blue',
 'birth_year': '19BBY',
 'gender': 'male',
 'homeworld': 'https://swapi.info/api/planets/1',
 'films': ['https://swapi.info/api/films/1',
  'https://swapi.info/api/films/2',
  'https://swapi.info/api/films/3',
  'https://swapi.info/api/films/6'],
 'species': [],
 'vehicles': ['https://swapi.info/api/vehicles/14',
  'https://swapi.info/api/vehicles/30'],
 'starships': ['https://swapi.info/api/starships/12',
  'https://swapi.info/api/starships/22'],
 'created': '2014-12-09T13:50:51.644000Z',
 'edited': '2014-12-20T21:17:56.891000Z',
 'url': 'https://swapi.info/api/people/1'}

In [30]:
## get specific data
response.json()["name"]

'Luke Skywalker'

In [31]:
response.json()["height"]

'172'

In [34]:
response.json()["eye_color"]

'blue'

In [42]:
## for loop
import requests
import time

names = []

for i in range(5):
  url = f"https://swapi.info/api/people/{i+1}"
  response = requests.get(url)
  response_json = response.json()
  names.append(response_json["name"])
  print(f"Success: {i+1}")
  time.sleep(1)

print(names)

Success: 1
Success: 2
Success: 3
Success: 4
Success: 5
['Luke Skywalker', 'C-3PO', 'R2-D2', 'Darth Vader', 'Leia Organa']

In [43]:
## explain i, i+1
for i in range(10):
  print(i, i+1)

0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8
8 9
9 10

# HW: Get data from any public API

In [46]:
# for loop
import requests
import time

characters = []

for i in range(5):
  url = f"https://swapi.info/api/people/{i+1}"
  response = requests.get(url)
  response_json = response.json()
  data = [response_json["name"],
          response_json["height"],
          response_json["mass"],
          response_json["eye_color"]
          ]
  characters.append(data)
  print(f"Success: {i+1}")
  time.sleep(1)

print(characters)

Success: 1
Success: 2
Success: 3
Success: 4
Success: 5
[['Luke Skywalker', '172', '77', 'blue'], ['C-3PO', '167', '75', 'yellow'], ['R2-D2', '96', '32', 'red'], ['Darth Vader', '202', '136', 'yellow'], ['Leia Organa', '150', '49', 'brown']]

In [47]:
import pandas as pd

starwars = pd.DataFrame(characters, columns=["name", "height", "mass", "eye_color"])
starwars

             name height mass eye_color
0  Luke Skywalker    172   77      blue
1           C-3PO    167   75    yellow
2           R2-D2     96   32       red
3     Darth Vader    202  136    yellow
4     Leia Organa    150   49     brown